:stylesheet: asciidoctor.css
:docinfo1:
// In generated HTML this is transformed
// to <meta name="description" content="..."/>
:description: Sample document with custom header and footer parts.
// In generated HTML this is transformed
// to <meta name="keywords" content="..."/>
:keywords: Asciidoctor, header, footer, docinfo

= Die Rolle des __Product Owner__ im Entwicklungsprozess einer Software-Applikation für das GSI-Operating
Martin Stein <m.stein@gsi.de>
v1.0, 2021-05-20
:toc-title: Inhaltsverzeichnis
:toc:
:icons: font
:imagesdir: common/img/
:docinfodir: common/meta/
:linkcss:
ifdef::env-github[]
:icons: font
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


== Der Software-Entwickungsprozess als Agile Methode

Im Bereich der Software-Entwicklung werden häufig Agile Methoden dem Wasserfall-Modell orientierten Vorgehensweisen vorgezogen.
So auch bei der hier betrachteten Methode der Applikationsentwicklung für das GSI-Operating.

.Wasserfall vs. Agile/Interative Vorgehensweise.

[#img-waterfall_vs_agile]
.Wasserfall vs. Agile/Interative Vorgehensweise. KSmith (WMF),CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons
image::waterfall_vs_agile.svg[waterfall_vs_agile,900]

[TIP]
Ein Block aus roter Planungsphase, gelber Designphase und grüner Herstellungsphase entspricht einer Iteration bei Agilen Methoden und wird im folgenden als __Sprint__ bezeichnet.

//image::scrum_process.svg[Embedded,1000,opts=inline]

== Die verschiedenen Rollen im Entwicklungsprozess einer Softwareapplikation

.Product (Team)
[NOTE]
Der Anglizismus _Product_ ist im Folgenden mit dem Wort Software-Applikation gleichzusetzen.


=== Die Rolle des __Stake Holder__ außerhalb des __Product Team__

Als erstes widmen wir uns der Rolle der __Stake Holder__, den Personen, für die die Software-Applikation gemacht wird oder entwickelt wurde. 

[TIP]
Betriebsleiter, Maschinen Koordinatoren, Mitglieder der FAIR Commissioning Group und Operateure sind nicht direkt Mitglieder des Product Teams.
Sie sind sogenannte _Stakeholder_ oder Nutzer und ihre Interessen werden vom _Product Owner_ im __Product Team__ vertreten.


Traditionell kommt die Rolle des _Stake Holder_ der Rolle des Kunden nahe.
Im Kontext einer innerbetrieblichen Entwicklung kommen die Bezeichnungen Nutzer, Nutznießer oder Anwender dieser Rolle aber meistens näher.
Diesen Bezeichnungen untersteht letztlich die Forderung, dass Wünsche und Anforderungen dieses Personenkreises in das zu entwickelnde Produkt im Rahmen des rational möglichen einzufließen haben.


=== Die Rollen innerhalb des __Product Team__ 

* __Mitglied des Entwicklerteams__ (z.B. aus dem Developer Pool)
* __Product Owner__


==== __Mitglied des Entwicklerteams__
__Mitglied des Entwicklerteams__ sind Personen, die direkt an den verschieden Entwicklungsaktivitäten beteiligt sind.
Sie führen u.a. Aktivitäten und Leistungen durch in den Bereichen:

** Software- / System-Design
** Benutzeroberflächen-Design
** Erstellung von sowohl technischer als auch Benutzer-Dokumentationen
** Programmierung
** Aufgaben der Qualitätssicherung

==== __Product Owner__

Der __Product Owner__ ist eine Art Bindeglied zwischen __Stake Holdern__ und __Entwicklerteam__ und steht dem __Entwicklerteam__ u.a. durch folgende Aktivitäten zur Seite.

. Erkennen, Entdecken, Sammeln und Beschreiben von Anforderungen, um zusammen mit dem __Entwicklerteam__, ein gemeinsames Verständnis über die Anforderungsumsetzungen, die Probleme und deren Lösungen zu entwickeln.

. Priorisierung der Anforderungen zur Optimierung der (zu einem bestimmten Zeitpunkt) auszuliefernden Software-Applikation.
Dabei ist häufig eine Konsensfindung zusammen mit dem __Entwicklerteam__ und im Zweifel mit den __Stakeholdern__ notwendig.

. Beurteilung, ob alle (bis zu einem bestimmten Zeitpunkt) eingeplanten Anforderungen zufriedenstellen abgedeckt wurden und korrekt ausgeliefert wurden.
Die Ergebnisse dieser Beurteilungen werden, wenn nötig und wenn eingeplant, in die nächste Arbeitsphase des __Product Teams__ mitgenommen. 
    
[#img-scrum_process]
.Agiler, Scrum orientierter Entwicklungsprozess aus der Sicht des Product Teams
image::scrum_process.svg[waterfall_vs_agile,1000]

== __Product Backlog__

Der Fokus dieser Dokumentation ist auf die Rolle des __Product Owner__ gerichtet ist.
Deshalb  wenden wir unseren Blick zuerst auf ein __Artifakt__ , welches eine zentrale Rolle für die Arbeit des __Product Owner__s spielt.
Den sogenannten __Product Backlog__.

.Artifakt (Scrum)
[NOTE]
===============================
Die im folgenden vorgestellte Softwareentwicklungsmethodologie ist stark an die agile Scrum Methode angelehnt.
Bei Scrum ist ein __Artifakt__, eine Art Prozessdokumentation.
Zu den Artifakten gehören mindestens der __Product Backlog__, der __Sprint Backlog__ und das __Increment__.
===============================

Der __Product Backlog__ ist im Prinzip eine Liste von Anforderungen.
Der __Product Owner__ ist zuständig für den __Product Backlog__, pflegt ihn und entwickelt ihn ständig weiter.

[#img-product_backlog]
.Product Backlog als Schnittstelle zwischen den Rollen
image::product_backlog.svg[product_backlog_and_roles,300]


Zur Erfüllung dieser Zuständigkeit braucht der __Product Owner__ regelmäßigen Input sowohl vom __Entwicklerteam__, als auch von den __Stakeholdern__.
Die einzelnen Einträge des  __Product Backlog__ werden __Product Backlog Item (PBI)__ genannt.
Welche formalen Regeln zu beachten sind, um __PBI__s  zu erstellen, soll *zunächst nicht Bestandteil dieser Dokumentation* sein, muss aber prinzipiell geklärt sein.
Ein __Product Backlog__ entwickelt sich nach und nach.
Seine Vollständigkeit ist keine Zielvorgabe, da man von einer dynamischen Entwicklung der Anforderungen während der gesamten Projektdauer ausgeht.
Die Einträge (__PBI__s) des __Product Backlog__  müssen regelmäßig unter Berücksichtigung von Faktoren wie Wert, Risiko, Machbarkeit und Abhängkeit priorisiert werden.
Der __Product Owner__ ist neben der Priorisierung gefordert bei der Beschreibung der einzelnen __Product Backlog Items (PBI)__.
Er muss versuchen sicherzustellen, dass sowohl die __Stakeholdern__ als auch das __Entwicklerteam__ das gleiche Verständnis über die  __Product_Backlog Items (PBI)__s entwickeln.
Der __Product Backlog__ wird während der gesamten Projektlaufzeit gepflegt. Die __Product_Backlog Items (PBI)__ werden Schritt für Schritt in __Sprints__ bearbeitet.

Hier ist ein unvollständiges Beispiel eines __Product Backlog__ unter der Benutzung von sogenannten __User Stories__ zur Beschreibung der gewünschten Funtionalitäten und Features.


[format="csv",[width="100%",cols="^1,<10,<10,^2"]
|===================================================
include::product_backlog_clean_up.csv[]
|===================================================


== __Sprint__
//Nun kommen wir aus Sicht des __Product Owner__s auf die Zusammenarbeit zwischen __Product Owner__ und dem __Product Team__.



== __Sprint Backlog__


== __Sprint Planning__, __Sprint Review__
